/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTodayRouteImport } from './routes/app.today'
import { Route as AppStatsRouteImport } from './routes/app.stats'
import { Route as AppProgressRouteImport } from './routes/app.progress'
import { Route as AppMonthRouteImport } from './routes/app.month'
import { Route as AppMeRouteImport } from './routes/app.me'
import { Route as AppGroceryRouteImport } from './routes/app.grocery'
import { Route as AppFridgeRouteImport } from './routes/app.fridge'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTodayRoute = AppTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AppRoute,
} as any)
const AppStatsRoute = AppStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppRoute,
} as any)
const AppMonthRoute = AppMonthRouteImport.update({
  id: '/month',
  path: '/month',
  getParentRoute: () => AppRoute,
} as any)
const AppMeRoute = AppMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AppRoute,
} as any)
const AppGroceryRoute = AppGroceryRouteImport.update({
  id: '/grocery',
  path: '/grocery',
  getParentRoute: () => AppRoute,
} as any)
const AppFridgeRoute = AppFridgeRouteImport.update({
  id: '/fridge',
  path: '/fridge',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/fridge': typeof AppFridgeRoute
  '/app/grocery': typeof AppGroceryRoute
  '/app/me': typeof AppMeRoute
  '/app/month': typeof AppMonthRoute
  '/app/progress': typeof AppProgressRoute
  '/app/stats': typeof AppStatsRoute
  '/app/today': typeof AppTodayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/fridge': typeof AppFridgeRoute
  '/app/grocery': typeof AppGroceryRoute
  '/app/me': typeof AppMeRoute
  '/app/month': typeof AppMonthRoute
  '/app/progress': typeof AppProgressRoute
  '/app/stats': typeof AppStatsRoute
  '/app/today': typeof AppTodayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/fridge': typeof AppFridgeRoute
  '/app/grocery': typeof AppGroceryRoute
  '/app/me': typeof AppMeRoute
  '/app/month': typeof AppMonthRoute
  '/app/progress': typeof AppProgressRoute
  '/app/stats': typeof AppStatsRoute
  '/app/today': typeof AppTodayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/fridge'
    | '/app/grocery'
    | '/app/me'
    | '/app/month'
    | '/app/progress'
    | '/app/stats'
    | '/app/today'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/fridge'
    | '/app/grocery'
    | '/app/me'
    | '/app/month'
    | '/app/progress'
    | '/app/stats'
    | '/app/today'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/fridge'
    | '/app/grocery'
    | '/app/me'
    | '/app/month'
    | '/app/progress'
    | '/app/stats'
    | '/app/today'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/today': {
      id: '/app/today'
      path: '/today'
      fullPath: '/app/today'
      preLoaderRoute: typeof AppTodayRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/stats': {
      id: '/app/stats'
      path: '/stats'
      fullPath: '/app/stats'
      preLoaderRoute: typeof AppStatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/progress': {
      id: '/app/progress'
      path: '/progress'
      fullPath: '/app/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/month': {
      id: '/app/month'
      path: '/month'
      fullPath: '/app/month'
      preLoaderRoute: typeof AppMonthRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/me': {
      id: '/app/me'
      path: '/me'
      fullPath: '/app/me'
      preLoaderRoute: typeof AppMeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/grocery': {
      id: '/app/grocery'
      path: '/grocery'
      fullPath: '/app/grocery'
      preLoaderRoute: typeof AppGroceryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/fridge': {
      id: '/app/fridge'
      path: '/fridge'
      fullPath: '/app/fridge'
      preLoaderRoute: typeof AppFridgeRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppFridgeRoute: typeof AppFridgeRoute
  AppGroceryRoute: typeof AppGroceryRoute
  AppMeRoute: typeof AppMeRoute
  AppMonthRoute: typeof AppMonthRoute
  AppProgressRoute: typeof AppProgressRoute
  AppStatsRoute: typeof AppStatsRoute
  AppTodayRoute: typeof AppTodayRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppFridgeRoute: AppFridgeRoute,
  AppGroceryRoute: AppGroceryRoute,
  AppMeRoute: AppMeRoute,
  AppMonthRoute: AppMonthRoute,
  AppProgressRoute: AppProgressRoute,
  AppStatsRoute: AppStatsRoute,
  AppTodayRoute: AppTodayRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
